name: nunchi-bench
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - google-generativeai>=0.3.2
      - openai>=1.14.0
      - anthropic
      - torch                  
      - transformers>=4.39.0   
      - accelerate             
      - sentencepiece          
      - bitsandbytes           
      - huggingface_hub
      - datasets               